### ISSUE TITLE
Criar roadmap

### ISSUE THREAD

**Issue by woliveiras** [iloveblogs/guest-post#1]
Criar roadmap com as necessidades do projeto

Pode ser em formato de issues

**Comment by teles** [comment]
Beleza, xeu anotar um rascunho aqui:

## MVP - Vê os blogs e insere um novo
1. [x] - Criar um "endpoint" com sheetsu
2. [x] - Adicionar angular e componente para get/post no sheetsu
3. [ ] - Exibir todos os dados em formato de tabela com campo para filtro
4. [ ] - Criar uma página para inserção de novo link
5. [ ] - Publicar no github-pages usando travis-ci

## Fase 2 - Filtrar blog por categoria
1. [ ] - Criar página de detalhe de blog
2. [ ] - Criar páginas para as categorias principais
3. [ ] - Sugerir categorias durante a inserção do blog (normalização)

## Fase 3 - Fazer curadoria de novos blogs
1. [ ] - Adicionar campo "deve_aparecer_no_site" na planilha, default: false
2. [ ] - Ver se compensa integrar com o formspree para receber por email novos blogs

## Fase 4 - Newsletter
1. [ ] - Integrar com api do mailchimp para possiblitar que usuários recebam informações sobre novos blogs
2. [ ] - Enviar email de "conheça nosso site e assine nossa newsletter" para emails cadastrados na planilha

## Fase 5 - Domain Authority
1. [ ] - Adicionar campo com domain authority de cada blogs cadastrado

O que acha, @woliveiras ?
